=== Axel29/WebserviceXML/core/schemas/schemavideogame.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <!-- Prix -->
    <xs:element name="price">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="devise" type="xs:string" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

<!-- @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ -->   

    <!-- Boutique où il est possible d'acheter le jeu-->
    <xs:element name="shop">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name"/>
                <xs:element ref="price"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
            <xs:attribute name="url" type="xs:anyURI" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- Contenu du commentaire -->
    <xs:element name="text" type="xs:string"/>

    <!-- Nombre de like du commentaire -->
    <xs:element name="like" type="xs:integer"/> 
    
    <!-- Nombre de dislike du commentaire -->
    <xs:element name="dislike" type="xs:integer"/>

<!-- @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ -->      

    <!-- Nom en général -->
    <xs:element name="name" type="xs:string"/>

    <!-- Contenu de l'édition -->
    <xs:element name="content" type="xs:string"/>

    <xs:element name="shops">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="shop" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Commentaire utilisateur -->
    <xs:element name="comment">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="text"/>
                <xs:element ref="date"/>
                <xs:element ref="userName"/>
                <xs:element ref="note"/>
                <xs:element ref="like"/>
                <xs:element ref="dislike"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- Point positif/négatif -->
    <xs:element name="analyse">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
                    <xs:attribute name="type" type="xs:string" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

<!-- @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ -->   

    <!-- Mode de jeu (solo, multi-joueurs, ...) -->
    <xs:element name="mode">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <!-- Jaquette avant / arrière -->
    <xs:element name="front">
        <xs:complexType>
            <xs:attribute name="url" type="xs:anyURI"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="back">
        <xs:complexType>
            <xs:attribute name="url" type="xs:anyURI"/>
        </xs:complexType>
    </xs:element>

    <!-- Type de support (physique, dématérialisé, ...) -->
    <xs:element name="support">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <!-- Information relative à une édition -->
    <xs:element name="edition">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name"/>
                <xs:element ref="content"/>
                <xs:element ref="shops"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="dlc">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="title"/>
                <xs:element ref="description"/>
                <xs:element ref="price"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- Détail de la configuration -->
    <xs:element name="config">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
                    <xs:attribute name="type" type="xs:string" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <!-- Résumé du test -->
    <xs:element name="report" type="xs:string"/>

    <!-- Date de publication -->
    <xs:element name="date" type="xs:dateTime"/>

    <!-- Nom du testeur -->
    <xs:element name="userName" type="xs:string"/>

    <!-- Note du testeur -->
    <xs:element name="note" type="xs:integer"/>

    <!-- Commentaires des utilisateurs -->
    <xs:element name="comments">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="comment" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Liste des points positifs/négatifs -->
    <xs:element name="analyses">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="analyse" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

<!-- @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ -->     

    <!-- Modèle économique du jeu (Free to play, ...) -->
    <xs:element name="businessModel" type="xs:string"/>

    <!-- Age minimum requis -->
    <xs:element name="pegi" type="xs:string"/>

    <xs:element name="modes">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="mode" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Jaquette du jeu -->
    <xs:element name="cover">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="front"/>
                <xs:element ref="back"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="supports">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="support" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Date de sortie du jeu -->
    <xs:element name="release" type="xs:date"/>

    <!-- Gestion de l'édition du jeu (collector, standard, ...) -->
    <xs:element name="editions">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="edition" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Description du contenu -->
    <xs:element name="description" type="xs:string"/>

    <!-- Liste les DLCs du jeu -->
    <xs:element name="dlcs">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="dlc" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Recommandations sur la configuration matérielle pour lancer le jeu --> 
    <xs:element name="configs">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="config" maxOccurs="2" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Test du jeu -->
     <xs:element name="test">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="report"/>
                <xs:element ref="date"/>
                <xs:element ref="userName"/>
                <xs:element ref="note"/>
                <xs:element ref="comments"/>
                <xs:element ref="analyses"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- Nom de console -->
    <xs:element name="consoleName" type="xs:string"/>

    <!-- Hauteur/Largeur du média -->
    <xs:element name="height" type="xs:float"/>
    <xs:element name="width" type="xs:float"/>

<!-- @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ -->      

    <!-- Genre du jeu (Action, FPS, ...) -->
    <xs:element name="gender">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <!-- Nom des studios d'édition du jeu -->
    <xs:element name="editor">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <!-- Thème de l'univers du jeu (Fantasy, Horeur, ...) -->
    <xs:element name="theme">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <!-- Eléments dépendants pour chaque console -->
    <xs:element name="console">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="businessModel"/>
                <xs:element ref="pegi"/>
                <xs:element ref="modes"/>
                <xs:element ref="cover"/>
                <xs:element ref="supports"/>
                <xs:element ref="release"/>
                <xs:element ref="editions"/>
                <xs:element ref="name"/>
                <xs:element ref="description"/>
                <xs:element ref="dlcs"/>
                <xs:element ref="configs"/>
                <xs:element ref="test"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- Langue -->
    <xs:element name="language">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <!-- Liste des consoles concernées par le contenu -->
    <xs:element name="consolesNames">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="consoleName" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Dimensions du média -->
    <xs:element name="dimensions">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute type="xs:string" name="unit" use="required"/>
                    <xs:attribute type="xs:string" name="width" use="required"/>
                    <xs:attribute type="xs:string" name="height" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

<!-- @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ -->     

    <xs:element name="genders">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="gender" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Titre du contenu -->
    <xs:element name="title" type="xs:string"/>

    <xs:element name="editors">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="editor" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="themes">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="theme" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Lien vers le site du jeu -->
    <xs:element name="site" type="xs:anyURI"/>

    <xs:element name="consoles">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="console" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Langues disponibles pour le jeu -->
    <xs:element name="languages">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="language" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Un article (news, article, ...) -->
    <xs:element name="article">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="consolesNames"/>
                <xs:element ref="title"/>
                <xs:element ref="userName"/>
                <xs:element ref="date"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
            <xs:attribute name="type" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- Media -->
    <xs:element name="media">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="consolesNames"/>
                <xs:element ref="dimensions"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
            <xs:attribute name="type" type="xs:string" use="required"/>
            <xs:attribute name="url" type="xs:anyURI" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- Astuce -->
    <xs:element name="tip">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="consolesNames"/>
                <xs:element ref="content"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
        </xs:complexType>
    </xs:element>


<!-- @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ -->      

    <!-- Fiche de présentation du jeu -->
    <xs:element name="presentation">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="genders"/>
                <xs:element ref="title"/>
                <xs:element ref="editors"/>
                <xs:element ref="themes"/>
                <xs:element ref="site"/>
                <xs:element ref="consoles"/>
                <xs:element ref="languages"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Liste des articles -->
    <xs:element name="articles">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="article" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Liste des médias -->
    <xs:element name="medias">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="media" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Liste des astuces -->
    <xs:element name="tips">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tip" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

<!-- @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ -->     

    <xs:element name="game">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="presentation"/>
                <xs:element ref="articles"/>
                <xs:element ref="medias"/>
                <xs:element ref="tips"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
        </xs:complexType>
    </xs:element>

<!-- @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ -->   

    <!-- Liste des jeux -->
    <xs:element name="list">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="game" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Axel29/WebserviceXML/core/videogame.xml
<?xml version="1.0" encoding="UTF-8"?>

<list xsi:noNamespaceSchemaLocation="schemavideogame.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<game>
		<presentation>
			<genders>
				<gender id="">Action</gender>
				<gender id="">MÃ©lodramatique</gender>
			</genders>
			<title>ThisIsAVideoGame</title>
			<editors>
				<editor id="">An editor</editor>
			</editors>
			<themes>
				<theme id=""></theme>
			</themes>
			<site></site>
			<consoles>
				<console id="">
					<businessModel></businessModel>
					<pegi></pegi>
					<modes>
						<mode id=""></mode>
					</modes>
					<cover>
						<front url="test" />
						<back url="/location/to/content" />
					</cover>
					<supports>
						<support id=""></support>
					</supports>
					<release>2015-01-25</release>
					<editions>
						<edition id="">
							<name></name>
							<content></content>
							<shops>
								<shop id="" url="test">
									<name></name>
									<price devise="euro"></price>
								</shop>
							</shops>
						</edition>
					</editions>
					<name></name>
					<description></description>
					<dlcs>
						<dlc id="">
							<title></title>
							<description></description>
							<price devise="euro"></price>
						</dlc>
					</dlcs>
					<configs>
						<config id="" type="minimale"></config>
						<config id="" type="optimale"></config>
					</configs>
					<test>	
						<report></report>
						<date>2015-01-22T11:33:33</date>
						<userName></userName>
						<note>1</note>
						<comments>
							<comment id="">
								<text></text>
								<date>2015-01-22T11:33:33</date>
								<userName></userName>
								<note>3</note>
								<like>0</like>
								<dislike>0</dislike>
							</comment>
						</comments>
						<analyses>
							<analyse id="" type="positive"></analyse>
							<analyse id="" type="negative"></analyse>
						</analyses>
					</test>
				</console>
			</consoles>
			<languages>
				<language id=""></language>
			</languages>
		</presentation>
		
		<articles>
			<article id="" type="news">
				<consolesNames>
					<consoleName></consoleName>
				</consolesNames>
				<title></title>
				<userName></userName>	
				<date>2015-01-22T11:33:33</date>		
			</article>
		</articles>
		
		<medias>
			<media id="" type="video" url="path/to/media" >
				<consolesNames>
					<consoleName></consoleName>
				</consolesNames>
				<dimensions unit="pt" width="32.4" height="90.5" />
			</media>
		</medias>
		
		<tips>
			<tip id="">
				<consolesNames>
					<consoleName></consoleName>
				</consolesNames>
				<content></content>
			</tip>
		</tips>
	</game>
</list>
